//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_GamingForm_Show
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_GamingFormEntities : DbContext
    {
        public DB_GamingFormEntities()
            : base("name=DB_GamingFormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AdminRank> AdminRanks { get; set; }
        public virtual DbSet<Advertise> Advertises { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleAction> ArticleActions { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Job_Opportunity> Job_Opportunities { get; set; }
        public virtual DbSet<JobAdvertise> JobAdvertises { get; set; }
        public virtual DbSet<JobCertificate> JobCertificates { get; set; }
        public virtual DbSet<JobResume> JobResumes { get; set; }
        public virtual DbSet<JobSkill> JobSkills { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberStatu> MemberStatus { get; set; }
        public virtual DbSet<MemberTag> MemberTags { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductAdvertise> ProductAdvertises { get; set; }
        public virtual DbSet<ProductEvaluate> ProductEvaluates { get; set; }
        public virtual DbSet<ProductTag> ProductTags { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RegionDistrict> RegionDistricts { get; set; }
        public virtual DbSet<Reply> Replies { get; set; }
        public virtual DbSet<ReplyAction> ReplyActions { get; set; }
        public virtual DbSet<ReplyImage> ReplyImages { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
        public virtual DbSet<ResumeCertificate> ResumeCertificates { get; set; }
        public virtual DbSet<ResumeSkill> ResumeSkills { get; set; }
        public virtual DbSet<ResumeStyle> ResumeStyles { get; set; }
        public virtual DbSet<SerachRecord> SerachRecords { get; set; }
        public virtual DbSet<ShipMethod> ShipMethods { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<SkillClass> SkillClasses { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SubBlog> SubBlogs { get; set; }
        public virtual DbSet<SubBolgCategory> SubBolgCategories { get; set; }
        public virtual DbSet<SubTag> SubTags { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
    }
}
